name: Auto Run Script Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x update_stats.sh

      - name: Run the Script
        run: ./update_stats.sh

      - name: Commit log file if updated
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add log.txt || echo "Nothing to add"
          git diff --staged --quiet || git commit -m "Auto update at $(date)"
          git push
