name: Auto Daily Commits

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Count Today's Commits
        id: commit_count
        run: |
          count=$(git log --since=midnight --oneline | wc -l)
          echo "Commits today: $count"
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Make Commit if Less Than 5
        if: ${{ steps.commit_count.outputs.count < 5 }}
        run: |
          echo "Committing dummy update..."
          echo "Update at $(date)" >> log.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add log.txt
          git commit -m "Auto update at $(date)"
          git push
